In [1]:
import pandas as pd
from pathlib import Path

PROCESSED_DATA_DIR = Path("../data/processed")

In [2]:
df = pd.read_parquet(PROCESSED_DATA_DIR / "strandings_with_weather.parquet")

In [3]:
min(df['mms_observation_dt'])

Timestamp('2016-01-10 00:00:00')

In [4]:
cycle = 29.530588
first_new_moon = pd.Timestamp("2016-01-10")
def moon_cycle(age):
    if age < 1.84566:
        return "New Moon"
    elif age < 5.53699:
        return "Waxing Crescent"
    elif age < 9.22831:
        return "First Quarter"
    elif age < 12.91963:
        return "Waxing Gibbous"
    elif age < 16.61096:
        return "Full Moon"
    elif age < 20.30228:
        return "Waning Gibbous"
    elif age < 23.99361:
        return "Last Quarter"
    elif age < 27.68493:
        return "Waning Crescent"
    else:
        return "New Moon"

In [5]:
def add_moon_cycle(df, mms_observation_dt):
    df = df.copy()
    df[mms_observation_dt] = pd.to_datetime(df[mms_observation_dt])

    days_since = (df[mms_observation_dt] - first_new_moon).dt.days
    moon_age = days_since % cycle

    df["moon_age"] = moon_age
    df["moon_phase"] = moon_age.apply(moon_cycle)

    return df

In [6]:
df

,National Database Number,Confidence Code,Common Name,Genus,Species,County,State,Latitude,Latitude Units,Latitude Actual/Estimate,...,temperature_2m_min_5_days_prior_delta,temperature_2m_min_4_days_prior,temperature_2m_min_4_days_prior_delta,temperature_2m_min_3_days_prior,temperature_2m_min_3_days_prior_delta,temperature_2m_min_2_days_prior,temperature_2m_min_2_days_prior_delta,temperature_2m_min_1_days_prior,temperature_2m_min_1_days_prior_delta,temperature_2m_min_0_days_prior
0,SE-2024-1283198,Confirmed Public Report,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.753987,decimal degrees,actual,...,-0.7,25.5,-1.1,27.4,1.9,25.8,-1.6,25.2,-0.6,24.6
1,SE-2016-1185796,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Carteret,NC,35.014470,decimal degrees,actual,...,-3.4,14.2,-2.4,16.0,1.8,18.7,2.7,21.2,2.5,20.5
2,SE-2016-1185799,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Hyde,NC,35.428380,decimal degrees,actual,...,-2.6,13.9,1.3,17.2,3.3,19.4,2.2,19.9,0.5,18.3
3,SE-2021-1236490,Confirmed - Minimum,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.657583,decimal degrees,actual,...,0.3,24.4,2.2,22.6,-1.8,21.9,-0.7,21.9,0.0,24.7
4,SE-2021-1236491,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.674153,decimal degrees,actual,...,0.3,20.8,-1.8,24.0,3.2,24.9,0.9,23.6,-1.3,23.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2217,NE-2018-1207271,Confirmed - Minimum,"Seal, harbor",Phoca,vitulina,Northampton,VA,37.325900,decimal degrees,actual,...,-3.3,1.8,-0.6,5.1,3.3,12.4,7.3,7.1,-5.3,4.6
2218,NE-2019-1210239,Confirmed - Medium Report,"Seal, harbor",Phoca,vitulina,Northampton,VA,37.182530,decimal degrees,actual,...,1.0,10.6,3.2,10.0,-0.6,9.1,-0.9,12.5,3.4,15.6
2219,SE-2022-1242580,Confirmed by Network,"Dolphin, common, short-beaked",Delphinus,delphis,Dare,NC,35.232766,decimal degrees,actual,...,1.9,9.6,0.8,11.1,1.5,5.7,-5.4,3.3,-2.4,4.1
2220,SE-2021-1236565,Confirmed - Minimum,"Whale, unidentified Kogia (dwarf/pygmy sperm)",Kogia,NaN,Georgetown,SC,33.425660,decimal degrees,estimate,...,0.7,25.0,-0.1,22.8,-2.2,22.5,-0.3,23.4,0.9,23.7
2221,NE-2019-1211216,Confirmed - High Report,"Seal, harbor",Phoca,vitulina,Accomack,VA,37.904478,decimal degrees,actual,...,0.8,17.6,3.7,17.5,-0.1,16.1,-1.4,13.6,-2.5,12.3

In [7]:
df = add_moon_cycle(df, "mms_observation_dt")

In [8]:
df

,National Database Number,Confidence Code,Common Name,Genus,Species,County,State,Latitude,Latitude Units,Latitude Actual/Estimate,...,temperature_2m_min_4_days_prior_delta,temperature_2m_min_3_days_prior,temperature_2m_min_3_days_prior_delta,temperature_2m_min_2_days_prior,temperature_2m_min_2_days_prior_delta,temperature_2m_min_1_days_prior,temperature_2m_min_1_days_prior_delta,temperature_2m_min_0_days_prior,moon_age,moon_phase
0,SE-2024-1283198,Confirmed Public Report,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.753987,decimal degrees,actual,...,-1.1,27.4,1.9,25.8,-1.6,25.2,-0.6,24.6,13.288260,Full Moon
1,SE-2016-1185796,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Carteret,NC,35.014470,decimal degrees,actual,...,-2.4,16.0,1.8,18.7,2.7,21.2,2.5,20.5,19.877648,Waning Gibbous
2,SE-2016-1185799,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Hyde,NC,35.428380,decimal degrees,actual,...,1.3,17.2,3.3,19.4,2.2,19.9,0.5,18.3,20.877648,Last Quarter
3,SE-2021-1236490,Confirmed - Minimum,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.657583,decimal degrees,actual,...,2.2,22.6,-1.8,21.9,-0.7,21.9,0.0,24.7,8.450604,First Quarter
4,SE-2021-1236491,Confirmed - High Report,"Dolphin, bottlenose",Tursiops,truncatus,Charleston,SC,32.674153,decimal degrees,actual,...,-1.8,24.0,3.2,24.9,0.9,23.6,-1.3,23.6,18.450604,Waning Gibbous
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2217,NE-2018-1207271,Confirmed - Minimum,"Seal, harbor",Phoca,vitulina,Northampton,VA,37.325900,decimal degrees,actual,...,-0.6,5.1,3.3,12.4,7.3,7.1,-5.3,4.6,14.898832,Full Moon
2218,NE-2019-1210239,Confirmed - Medium Report,"Seal, harbor",Phoca,vitulina,Northampton,VA,37.182530,decimal degrees,actual,...,3.2,10.0,-0.6,9.1,-0.9,12.5,3.4,15.6,3.776480,Waxing Crescent
2219,SE-2022-1242580,Confirmed by Network,"Dolphin, common, short-beaked",Delphinus,delphis,Dare,NC,35.232766,decimal degrees,actual,...,0.8,11.1,1.5,5.7,-5.4,3.3,-2.4,4.1,13.205900,Full Moon
2220,SE-2021-1236565,Confirmed - Minimum,"Whale, unidentified Kogia (dwarf/pygmy sperm)",Kogia,NaN,Georgetown,SC,33.425660,decimal degrees,estimate,...,-0.1,22.8,-2.2,22.5,-0.3,23.4,0.9,23.7,11.920016,Waxing Gibbous
2221,NE-2019-1211216,Confirmed - High Report,"Seal, harbor",Phoca,vitulina,Accomack,VA,37.904478,decimal degrees,actual,...,3.7,17.5,-0.1,16.1,-1.4,13.6,-2.5,12.3,1.245892,New Moon

In [9]:
from se_coast_strandings.contextual_data.lunar_phases import add_moon_features

# Re-apply using the module function for consistency
df = add_moon_features(df, date_col="mms_observation_dt")
df.to_parquet(PROCESSED_DATA_DIR / "strandings_with_moon.parquet", index=True)
print(f"Saved strandings_with_moon.parquet: {len(df)} rows")

Saved strandings_with_moon.parquet: 2222 rows